version: "3.4"

services:
    minimal-api:
        container_name: minimal_api
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - minimaldb

    minimaldb:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        container_name: minimal_database
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"